{% set version = "2.1.0" %}

package:
  name: termcolor-cpp
  version: {{ version }}

source:
  url: https://github.com/ikalnytskyi/termcolor/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 435994c32557674469404cb1527c283fdcf45746f7df75fd2996bb200d6a759f

build:
  number: 0

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    - make  # [unix]

test:
  commands:
    - test -e $PREFIX/include/termcolor/termcolor.hpp  # [not win]
    - if not exist %PREFIX%\Library\include\termcolor\termcolor.hpp exit 1  # [win]

about:
  home: https://github.com/ikalnytskyi/termcolor
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Header-only C++ library for printing colored messages to the terminal.

extra:
  recipe-maintainers:
    - adriendelsalle
